// const name = "setu";
// const surname = "singh";
// console.log(`hello my name is ${name} and my surname is ${surname}`);
// const newname = new String("singhsetu");
// console.log(newname.__proto__);
// console.log(newname.length);
// console.log(newname.toUpperCase());
// console.log(newname.charAt(4));
// console.log(newname.indexOf("i"));
// console.log(newname.substring(4, 7));
// console.log(newname.slice(2, -4)); //negative use back side
// const newstring = "  singhsetu  ";
// console.log(newstring);
// console.log(newstring.trim());

// const url="https://x.com/explore"
// console.log(url.replace("https","http"))
// console.log(url.includes("setu"));//to find

//number

// const score=4846;
// console.log(score);

// const balance=new Number(70045523)
// console.log(balance.toPrecision(5));//approx
// console.log(balance.toLocaleString('en-IN'));

// //maths

// console.log(Math.abs(-56));
// console.log(Math.round(4.548));
// console.log(Math.ceil(4.256));
// console.log(Math.floor(454.999));

console.log(Math.random());
console.log(Math.random() * 10 + 1);

const min = 10;
const max = 50;

console.log(Math.floor(Math.random() * (max - min + 1)) + min);
